#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/85b31f4d-a4ee-4af1-9f95-1daff140aa2a/ # 
title: Email
/email:
  get:
    responses:
      200:
        body:
          application/json:
            type: string
            example: "Email sent"
              